config/routes.rb
Rails.application.routes.draw do
  resources :markers do
    resources :comments
  end

  resources :users
  resources :sessions, only: [:create]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_password_token
    post 'password' => :create
  end
  get "password/:token", to: "passwords#new", as: "password_token"

  resources :custom_pages, except: [:show] do
    get 'url_available/:url_to_check', to: 'custom_pages#url_available', as: 'url_available'
  end
  get 'custom_pages/url_available/:url_to_check', to: 'custom_pages#url_available'
  get ':id', to: 'custom_pages#show', as: 'show_custom_page'

  root 'markers#index'

end

app/models/marker.rb
class Marker < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::SanitizeHelper

  VIDEO_DIMENSIONS = {
    content: { width: 360, height: 216 }
  }

  belongs_to :user
  has_one :marker_category
  has_many :comments
  has_many :pictures
  accepts_nested_attributes_for :pictures

  validates_presence_of :title, :lat, :lng
  validates_uniqueness_of :url, on: :update

  before_create do
    self.content = strip_tags(simple_format(self.content))
  end
  after_create do
    self.url = self.to_param
    self.save
  end
  before_create :parse_video_url_to_iframe
  before_update :parse_video_url_to_iframe

  def full_title
    "#{title} - #{CustomPage::DEFAULT_TITLE}"
  end

  def gps
    "#{lat.round(7)}N, #{lng.round(7)}E"
  end

  def parse_video_url_to_iframe
    if self.video_url =~ /youtube\.com\/watch(.+)/
      position = 8 + (self.video_url =~ /watch/)
      youtube_id = self.video_url[position..-1]
      self.video_iframe = "<iframe width='VIDEO_WIDTH' height='VIDEO_HEIGHT' src='https://www.youtube.com/embed/" + youtube_id + "' frameborder='0' allowfullscreen></iframe>"
    elsif self.video_url =~ /vimeo\.com\/(.+)/
      vimeo_id = self.video_url.scan(/\d/).join
      self.video_iframe = '<iframe src="https://player.vimeo.com/video/' + vimeo_id + '" width="VIDEO_WIDTH" height="VIDEO_HEIGHT" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
    elsif self.video_url =~ /(<iframe(.+)>(.*)<\/iframe>)|(<embed(.+)>(.*)<\/embed>)|(<video(.+)>(.+)<\/video>)/
      self.video_iframe = self.video_url
      self.video_url = nil
    end

    if self.video_url.present? && self.video_url !~ /^http/
      self.video_url = "http://#{video_url}"
    end
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def video_iframe_formatted(format)
    raise ArgumentError unless VIDEO_DIMENSIONS.has_key? format

    video_iframe.gsub("VIDEO_WIDTH", VIDEO_DIMENSIONS[format][:width].to_s)
      .gsub("VIDEO_HEIGHT", VIDEO_DIMENSIONS[format][:height].to_s)
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :authorize, only: [:edit, :update, :destroy]
  before_action :set_marker, only: [:show, :edit, :update, :destroy]
  before_action :set_marker_categories, only: [:new, :create, :edit, :update]

  load_and_authorize_resource

  # GET /markers
  def index
    @markers = Marker.all
  end

  # GET /markers/1
  def show
    @author_name = current_user.present? ? current_user.name : ""
    respond_to do |format|
      format.html { render "show", layout: false if params[:l] == "f" }
      format.js
    end
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    build_marker_pictures
    render "new", layout: false if params[:l] == "f"
  end

  # GET /markers/1/edit
  def edit
    respond_to do |format|
      format.html { render "edit", layout: false if params[:l] == "f" }
      format.js
    end
  end

  # POST /markers
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: t("markers.create.ok") }
        format.js { flash.now.notice = t("markers.create.ok") }
      else
        format.html { render :new }
        format.js
      end
    end
  end

  # PATCH/PUT /markers/1
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: t("markers.update.ok") }
        format.js { flash.now.notice = t("markers.update.ok")}
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /markers/1
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: t("markers.destroy.ok") }

      # DO NOT USE
      # CURRENTLY NO WAY TO REMOVE DESTROYED MARKER FROM THE MAP ON FRONTEND
      format.js { flash.now.notice = t("markers.destroy.ok") }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    def set_marker_categories
      @marker_categories = [[t("markers.choose_type"), nil]]
      MarkerCategory.all.order(:title).collect do |category|
        @marker_categories << [category.title, category.id]
      end
    end

    def build_marker_pictures
      6.times { @marker.pictures.build }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      parameters = params.require(:marker)
        .permit(:title, :content, :marker_category_id, :lat, :lng, :video_url, :video_iframe,
                pictures_attributes: [:id, :picture])

      if current_user.present?
        parameters.merge(user_id: current_user.id)
      else
        parameters
      end
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_admin_marker_menu.html.erb
<% if @current_user.present? && can?(:manage, @marker) %>
  <nav id="content_menu">
    <ul>
      <li><%= link_to t("markers.admin_menu.edit"), edit_marker_url(@marker), remote: true %></li>
      <li><%= link_to t("markers.admin_menu.destroy"), marker_url(@marker), method: :delete, data: { confirm: t("actions.confirm") } %></li>
    </ul>
  </nav>
  <div class="cleaner"></div>
<% end %>

app/views/markers/_edit.html.erb
<%= render "flash" %>

<h2><%= t("markers.edit") %></h2>

<%= render 'form' %>

<%= link_to t("actions.back"), marker_path(@marker), remote: true %>

app/views/markers/_form.html.erb
<%= form_for(@marker, remote: true, authenticity_token: true) do |f| %>
  <%= render "form_errors" %>

  <div class="field">
    <%= f.label :title, t("markers.title") %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content, t("markers.content") %><br>
    <%= f.text_area :content, rows: 10, cols: 50 %>
  </div>
  <div class="field">
    <%= f.label :marker_category_id, t("markers.marker_type") %>
    <%= f.select :marker_category_id, options_for_select(@marker_categories, @marker.marker_category_id) %>
  </div>

  <% if [:new, :create].include? controller.action_name.to_sym %>
    <%= render partial: "pictures_form_new", locals: {f: f} %>
  <% else %>
    <%= render partial: "pictures_form_edit" %>
  <% end %>

  <div class="field">
    <%= f.label :video_url, t("markers.video_url") %><br>
    <%= f.text_field :video_url %>
    <p><%= t("markers.video_url_description").html_safe %></p>
  </div>

  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>

  <div class="actions">
    <%= f.submit t("actions.submit") %>
  </div>
    <div class="cleaner"></div>
<% end %>

app/views/markers/_form_errors.html.erb
<% if @marker.errors.any? %>
  <div id="error_explanation">
    <h3><%= t("actions.errors") %></h3>

    <ul>
    <% @marker.errors.messages.each do |message| %>
      <li><%= message[1].first %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/markers/_load_markers.html.erb
<script>
    $(document).ready(function(){
      var markers = [];
      <% @markers.each do |marker| %>
        markers.push(
          <%= marker.to_json(include: { pictures: {methods: [:url_thumb, :url_medium]}}, methods: :full_title).html_safe %>
        );
      <% end %>

      for (i in markers) {
        loadMarker(markers[i], map);
      }
    });
</script>

app/views/markers/_pictures_form_edit.html.erb
<% if @marker.pictures.present? %>
  <div id="pictures">
    <ul>
      <% @marker.pictures.each do |picture| %>
      <li>
        <%= link_to(image_tag(picture.picture.url(:thumb)), image_path(picture.picture.url(:medium)), rel: "gallery#{@marker.id}", class: "fancybox") %>
      </li>
      <% end %>
    </ul>
    <div class="cleaner"></div>
  </div>
<% end %>

app/views/markers/_pictures_form_new.html.erb
<div id="pictures_form" data-fields-to-show="5">
  <%= f.fields_for :pictures do |pictures_form| %>
    <div class="field">
      <%= pictures_form.label :picture, t("markers.picture") %>
      <%= pictures_form.file_field :picture %>
    </div>
  <% end %>
</div>

app/views/markers/_show.html.erb
<%= render "flash" %>
<%= render "admin_marker_menu" %>

<div id="left">
  <h2><%= @marker.title %></h2>
  <p id="gps">GPS: <%= @marker.gps %></p><br>
  <div id="text"><%= simple_format(@marker.content) %></div>

  <%= render "comments/comments" %>
</div>

<div id="right">
  <% if @marker.pictures.present? %>
    <div id="pictures">
      <h3><%= t("markers.pictures") %></h3>
      <ul>
        <% @marker.pictures.all.each_with_index do |picture, i| %>
          <% if i % 2 == 0 %><li><% else %><li class="odd"><% end %>
          <%= link_to(image_tag(picture.picture.url(:thumb)), image_path(picture.picture.url(:medium)), rel: "gallery#{@marker.id}", class: "fancybox") %></li>
        <% end %>
      </ul>
      <div class="cleaner"></div>
    </div>
  <% end %>

  <% if @marker.video_iframe.present? %>
    <h3><%= t("markers.video") %></h3>
    <div id="video">
      <%= @marker.video_iframe_formatted(:content).html_safe %>
    </div>
  <% end %>
</div>
<div class="cleaner"></div>

app/views/markers/_show_with_flash.js.erb
loadMarker(<%= @marker.to_json.html_safe %>, map);
history.pushState({}, "", "<%= marker_path @marker %>");
$("div#content").empty().html("<%=j render 'show' %>");
$("div#flash_message").delay(2000).fadeOut(1000);

app/views/markers/create.js.erb
<% if @marker.valid? %>
  <%= render "show_with_flash" %>
<% else %>
  $("div#error_explanation").remove();
  $("div#content h2").after("<%=j render "form_errors" %>");
  $("div#content").scrollTop();
  $("div#content form#new_marker img.loading").remove();
  $("div#content form#new_marker").find("input[name='commit']").removeAttr("disabled");
<% end %>

app/views/markers/edit.html.erb
<%= render "edit" %>

app/views/markers/index_list.html.erb
<%= render "flash" %>

<h1><%= t("markers.index") %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('models.markers.title') %></th>
      <th><%= t('models.markers.content') %></th>
      <th><%= t('models.markers.marker_type') %></th>
      <th><%= t('models.markers.pictures') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= marker.title %></td>
        <td><%= marker.content %></td>
        <td><%= marker.marker_category_id %></td>
        <td><%= marker.pictures.length %></td>
        <td><%= link_to t('actions.show'), marker %></td>
        <td><%= link_to t('actions.edit'), edit_marker_path(marker) %></td>
        <td><%= link_to t('actions.destroy'), marker,
                        method: :delete, data: { confirm: t('actions.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('models.markers.new'), new_marker_path %>

app/views/markers/show.js.erb
<%= render "default_response" %>

app/views/markers/update.js.erb
<% if @marker.valid? %>
  <%= render "show_with_flash" %>
<% else %>
  $("div#error_explanation").remove();
  $("div#content h2").after("<%=j render "form_errors" %>");
  $("div#content").scrollTop();
  $("div#content form#new_marker img.loading").remove();
  $("div#content form#new_marker").find("input[name='commit']").removeAttr("disabled");
<% end %>