config/routes.rb
Rails.application.routes.draw do
  resources :markers do
    resources :comments
  end

  resources :users
  resources :sessions, only: [:create]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_password_token
    post 'password' => :create
  end
  get "password/:token", to: "passwords#new", as: "password_token"

  resources :custom_pages, except: [:show] do
    get 'url_available/:url_to_check', to: 'custom_pages#url_available', as: 'url_available'
  end
  get 'custom_pages/url_available/:url_to_check', to: 'custom_pages#url_available'
  get ':id', to: 'custom_pages#show', as: 'show_custom_page'

  root 'markers#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %i[user admin]

  has_secure_password

  has_many :markers
  has_many :markers

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :password, on: :create

  def admin?
    role == "admin"
  end

  def guest?
    !admin? && !user?
  end

  def user?
    role == "user"
  end

  def title_for_user_menu
    name.present? ? "#{name} (#{email})" : email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index, :update]
  before_action :set_roles, only: [:edit, :update]
  load_and_authorize_resource except: [:new, :create]

  def index
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.registration_email(@user).deliver
        format.html { redirect_to root_url, notice: t("users.create.ok") }
        format.js { flash.now.notice = t("users.create.ok") }
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        destination = current_user.admin? ? users_url : @user

        format.html { redirect_to destination, notice: t("users.update.ok") }
        format.js { flash.now.notice = t("users.update.ok") }
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    if current_user.user? || (current_user.admin? && @user.id == current_user.id)
      session[:user_id] = nil
      destination = root_url
    elsif current_user.admin? && @user.id != current_user.id
      destination = users_url
    end
    @user.destroy

    respond_to do |format|
      format.html { redirect_to destination, notice: t("users.destroy.ok") }
      format.js { flash.now.notice = t("users.destroy.ok") }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_users
    @users = User.order(:role, :email)
  end

  def set_roles
    @roles = []
    User::ROLES.each { |role| @roles << [t("users.roles.#{role}"), role] }
    @roles
  end

  def user_params
    parameters = params.require(:user).permit(:name, :email)
    parameters.merge!(role: params[:user][:role]) if current_user.present? && current_user.admin?

    if current_user.blank?
      parameters.merge!(
        password: params[:user][:password],
        password_confirmation: params[:user][:password_confirmation]
      )
    end
    parameters
  end

  # refactor na volani super
  def set_title
    titles = {
      new: "Registrace uživatele",
      edit: "Úprava údajů",
      index: "Seznam uživatelů",
      show: "Detail účtu"
    }
    @title = "#{titles[action_name.to_sym]} - #{CustomPage::DEFAULT_TITLE}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<%= render "flash" %>

<h2><%= t("users.edit.edit_user") %></h2>

<%= form_for(@user, url: user_url(@user), method: :put, remote: true) do |f| %>
  <%= render partial: "form", locals: { f: f } %>

  <% if @current_user.admin? %>
    <div class="field">
      <%= f.label :role %>
      <%= f.select :role, options_for_select(@roles, @user.role) %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t("actions.submit") %>
  </div>
<% end %>

<%= link_to t("users.index.list_of_users"), users_path, remote: true %>

app/views/users/_form.html.erb
  <%= render "form_errors" %>

  <div class="field">
    <%= f.label :name, t("forms.name") %><br>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email, t("forms.email") %><br>
    <%= f.text_field :email %>
  </div>

app/views/users/_form_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h3><%= t("actions.errors") %></h3>

    <ul>
    <% @user.errors.messages.each do |message| %>
      <li><%= message[1].first %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_index.html.erb
<%= render "flash" %>

<h2><%= t("users.index.list_of_users") %></h2>

<table>
  <tr>
    <th><%= t("users.index.email") %></th>
    <th><%= t("users.index.name") %></th>
    <th><%= t("users.index.role") %></th>
    <th><%= t("users.index.created_at") %></th>
    <th><%= t("actions.actions") %></th>
<% @users.order(:email).each do |user| %>
  <tr id="user<%=user.id%>">
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= t("users.roles.#{user.role}") %></td>
    <td class="t-center"><%= user.created_at.strftime("%-d.%-m.%Y %H:%M") %></td>
    <td><%= link_to t("actions.edit"), edit_user_url(user), remote: true %>&nbsp;<%= link_to t("actions.destroy"), user_url(user), method: :delete, remote: true, data: { confirm: t("actions.confirm") } %></td>
  </tr>
<% end %>
</table>

app/views/users/_show.html.erb
<%= render "flash" %>

<h2><%= t("users.show.profile") %></h2>

<p><%= t("users.index.name").capitalize %>: <%= @user.name %></p>
<p><%= t("users.index.email").capitalize %>: <%= @user.email %></p>
<br>
<p><%= link_to t("actions.edit"), edit_user_url(@user), remote: true %></p>
<br>
<p><%= link_to t("users.destroy.destroy_account"), user_url(@user), method: :delete, style: "color: red", data: { confirm: t("actions.confirm") } %>&nbsp;<%= t("users.destroy.destroy_account_description") %></p>

app/views/users/create.js.erb
<% if @user.valid? %>
  <%= render "flash_response" %>
<% else %>
  $("div#content div#error_explanation").remove();
  $("div#content h2").after("<%=j render 'form_errors' %>");
  $("div#content").scrollTop();
  $("div#content form#new_user img.loading").remove();
  $("div#content form#new_user").find("input[name='commit']").removeAttr("disabled");
<% end %>

app/views/users/edit.html.erb
<%= render "edit" %>

app/views/users/index.html.erb
<%= render "index" %>

app/views/users/index.js.erb
$("title").html("<%= @title %>");
<%= render "default_response" %>

app/views/users/new.html.erb
<%= render "new" %>

app/views/users/new.js.erb
$("title").html("<%= @title %>");
<%= render "default_response" %>

app/views/users/show.html.erb
<%= render "show" %>

app/views/users/show.js.erb
$("title").html("<%= @title %>");
<%= render "default_response" %>

app/views/users/update.js.erb
<% if @user.valid? %>
  history.pushState({}, "", "<%= user_url(@user) %>");
  <% if @current_user.admin? %>
    $("div#content").empty().html("<%=j render 'index' %>")
  <% else %>
    $("div#content").empty().html("<%=j render 'show' %>");
  <% end %>
  $("div#flash_message").delay(2000).fadeOut(1000);
<% else %>
  $("div#content h2").after("<%=j render "form_errors" %>");
  $("div#content").scrollTop();
  $("div#content form.edit_user img.loading").remove();
  $("div#content form.edit_user").find("input[name='commit']").removeAttr("disabled");
<% end %>