config/routes.rb
Rails.application.routes.draw do
  resources :markers do
    resources :comments
  end

  resources :users
  resources :sessions, only: [:create]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_password_token
    post 'password' => :create
  end
  get "password/:token", to: "passwords#new", as: "password_token"

  resources :custom_pages, except: [:show] do
    get 'url_available/:url_to_check', to: 'custom_pages#url_available', as: 'url_available'
  end
  get 'custom_pages/url_available/:url_to_check', to: 'custom_pages#url_available'
  get ':id', to: 'custom_pages#show', as: 'show_custom_page'

  root 'markers#index'

end

app/models/custom_page.rb
class CustomPage < ActiveRecord::Base
  validates_presence_of :title, :page_url, :body
  validates_uniqueness_of :page_url

  # presunout do cs.yml
  DEFAULT_TITLE = "Zasaď své město"

  def inactive?
    !active?
  end

  def self.pages_for_menu
    where('show_in_menu = ?', true).select('title, page_url, body').order('position_in_menu')
  end

  def title
    super.gsub(" ", "\u00A0")
  end

  def full_title
    "#{title} - #{DEFAULT_TITLE}"
  end

  def to_param
    page_url
  end

  def url_to_url_available
    new_record? ? "/custom_pages/url_available" : "/custom_pages/#{to_param}/url_available"
  end
end

app/controllers/custom_pages_controller.rb
class CustomPagesController < ApplicationController
  before_action :set_custom_page, only: [:show, :edit, :update, :destroy]
  before_action :set_custom_pages, only: [:index, :destroy]
  before_action :set_title, only: [:show, :edit]
  load_and_authorize_resource

  # GET /pages
  def index
    @title = "Seznam stránek - #{CustomPage::DEFAULT_TITLE}"

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /pages/1
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /pages/new
  def new
    @custom_page = CustomPage.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /pages/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /pages
  def create
    @custom_page = CustomPage.new(custom_page_params)

    respond_to do |format|
      if @custom_page.save
        format.html { redirect_to show_custom_page_url(@custom_page), notice: t("custom_pages.create.ok") }
        format.js { flash.now.notice = t("custom_pages.create.ok") }
      else
        format.html { render :new }
        format.js
      end
    end
  end

  # PATCH/PUT /pages/1
  def update
    respond_to do |format|
      if @custom_page.update(custom_page_params)
        format.html { redirect_to show_custom_page_url(@custom_page), notice: t("custom_pages.create.ok") }
        format.js { flash.now.notice = t("custom_pages.create.ok") }
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /pages/1
  def destroy
    @custom_page.destroy
    respond_to do |format|
      format.html { redirect_to custom_pages_url, notice: t("custom_pages.destroy.ok") }
      format.js { flash.now.notice = t("custom_pages.destroy.ok") }
    end
  end

  def url_available
    respond_to do |format|
      format.json do
        render json: { urlAvailable: !CustomPage.exists?(page_url: params[:url_to_check]) }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_page
      if current_user.present? && current_user.admin?
        @custom_page = CustomPage.find_by_page_url(params[:id])
      else
        @custom_page = CustomPage.where(active: true).find_by_page_url(params[:id])
      end
      @custom_page ||= not_found
    end

    def set_custom_pages
      @custom_pages = CustomPage.order(:page_url)
    end

    def set_title
      @title = @custom_page.full_title
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_page_params
      params.require(:custom_page).permit(:title, :body, :active, :show_in_menu, :page_url, :position_in_menu)
    end
end

app/helpers/custom_pages_helper.rb
module CustomPagesHelper
end

app/views/custom_pages/_admin_custom_page_menu.html.erb
<% if @current_user.present? && can?(:manage, @custom_page) %>
  <nav id="content_menu">
    <p><strong><%= t("custom_pages.active") %>:</strong> <%= @custom_page.active? ? t("yes") : t("no") %></p>
    <p><strong><%= t("custom_pages.show_in_menu") %>:</strong> <%= @custom_page.show_in_menu? ? t("yes") : t("no") %></p>
    <p><strong><%= t("custom_pages.page_url") %>:</strong> /<%= @custom_page.page_url %></p>
    <p><strong><%= t("custom_pages.position_in_menu") %>:</strong> <%= @custom_page.position_in_menu ? "#{@custom_page.position_in_menu}." : t('custom_pages.no_position') %></p>

    <%= link_to t("custom_pages.edit.edit_page"), edit_custom_page_url(@custom_page), remote: true %><br>
    <%= link_to t("custom_pages.destroy.destroy_page"), custom_page_url(@custom_page), method: :delete, remote: true, data: { confirm: t("actions.confirm") } %><br>
    <%= link_to t("custom_pages.index.pages_list"), custom_pages_url, remote: true %>
  </nav>
  <div class="cleaner"></div>
<% end %>

app/views/custom_pages/_edit.html.erb
<h2><%= t("custom_pages.edit.edit_page") %></h2>

<%= render 'form' %>

<%= link_to t("custom_pages.show.show_page"), show_custom_page_url(@custom_page), remote: true %> |
<%= link_to t("custom_pages.index.pages_list"), custom_pages_path, remote: true %>

app/views/custom_pages/_form.html.erb
<%= form_for(@custom_page, remote: true) do |f| %>
  <%= render "form_errors" %>

  <div class="field">
    <%= f.label :title, t("custom_pages.title") %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :page_url, t("custom_pages.page_url") %><br>
    /<%= f.text_field :page_url %>
  </div>
  <div class="field">
    <%= f.label :body, t("custom_pages.body") %><br>
    <%= f.text_area :body, cols: 100, rows: 15 %>
  </div>
  <div class="field">
    <%= f.check_box :active %>
    <%= f.label :active, t("custom_pages.active") %>
  </div>
  <div class="field">
    <%= f.check_box :show_in_menu %>
    <%= f.label :show_in_menu, t("custom_pages.show_in_menu") %>
  </div>
  <div class="field">
    <%= f.label :position_in_menu, t("custom_pages.position_in_menu") %><br>
    <%= f.number_field :position_in_menu %>
  </div>
  <div class="actions">
    <%= f.submit t("actions.submit") %>
  </div>
<% end %>

<%= javascript_tag do -%>
  $('input#custom_page_page_url').keyup(function() {
    isUrlAvailable(
      $(this),
      '<%= j @custom_page.url_to_url_available %>',
      '<%= j @custom_page.page_url %>',
      '<%= j t("custom_pages.available") %>',
      '<%= j t("custom_pages.unavailable") %>'
    );
  })
<% end -%>

app/views/custom_pages/_index.html.erb
<h2><%= t("custom_pages.index.pages_list") %></h2>

<table id="pages_list">
  <thead>
    <tr>
      <th><%= t("custom_pages.title").downcase %></th>
      <th><%= t("custom_pages.page_url") %></th>
      <th><%= t("custom_pages.active").downcase %></th>
      <th><%= t("custom_pages.show_in_menu").downcase %></th>
      <th><%= t("custom_pages.position_in_menu").downcase %></th>
      <th><%= t("actions.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_pages.each do |custom_page| %>
      <tr id="page<%= custom_page.id %>">
        <td><%= link_to custom_page.title, show_custom_page_url(custom_page), remote: true %></td>
        <td>/<%= custom_page.page_url %></td>
        <td class="t-center"><%= custom_page.active? ? t("yes") : t("no") %></td>
        <td class="t-center"><%= custom_page.show_in_menu ? t("yes") : t("no") %></td>
        <td class="t-center"><%= custom_page.position_in_menu.present? ? "#{custom_page.position_in_menu}." : "-" %></td>
        <td><%= link_to t("actions.edit"), edit_custom_page_path(custom_page), remote: true %>
          <%= link_to t("actions.destroy"), custom_page_url(custom_page), method: :delete, remote: true, data: { confirm: t("actions.confirm") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("custom_pages.new.new_page"), new_custom_page_path, remote: true %>

app/views/custom_pages/_new.html.erb
<h2><%= t("custom_pages.new.new_page") %></h2>

<%= render 'form' %>

<%= link_to t("custom_pages.index.pages_list"), custom_pages_path, remote: true %>

app/views/custom_pages/_save.js.erb
<% if @custom_page.valid? %>
  <%= render "show_with_flash" %>
  $("nav#main_menu ul > li:first ul").html("<%=j render 'website_menu' %>");
<% else %>
  $("div#error_explanation").remove();
  $("div#content h2").after("<%=j render "form_errors" %>");
  $("div#content").scrollTop();
  $("div#content form#new_page img.loading").remove();
  $("div#content form#new_page").find("input[name='commit']").removeAttr("disabled");
<% end %>

app/views/custom_pages/_show.html.erb
<%= render "flash" %>
<%= render "admin_custom_page_menu" %>

<h2><%= @custom_page.title %></h2>
<p><%= @custom_page.body.html_safe %></p>

app/views/custom_pages/_show_with_flash.js.erb
history.pushState({}, "", "<%= show_custom_page_url(@custom_page) %>");
$("div#content").empty().html("<%=j render 'show' %>");
$("div#flash_message").delay(2000).fadeOut(1000);

app/views/custom_pages/create.js.erb
<%= render "save" %>

app/views/custom_pages/destroy.js.erb
if (!$("table#pages_list").length) {
  $("div#content").empty().html("<%=j render 'index' %>")  ;
}
$("div#content").prepend("<%=j render 'flash' %>");
$("div#flash_message").delay(2000).fadeOut(1000);
$("table#pages_list tr#page<%= @custom_page.id %>").fadeOut(1000);

app/views/custom_pages/edit.html.erb
<%= render "edit" %>

app/views/custom_pages/edit.js.erb
<%= render "default_response" %>

app/views/custom_pages/new.js.erb
<%= render "default_response" %>

app/views/custom_pages/show.js.erb
$("title").html("<%= @custom_page.full_title %>");
<%= render "default_response" %>