config/routes.rb
Rails.application.routes.draw do
  resources :markers do
    resources :comments
  end

  resources :users
  resources :sessions, only: [:create]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_password_token
    post 'password' => :create
  end
  get "password/:token", to: "passwords#new", as: "password_token"

  resources :custom_pages, except: [:show] do
    get 'url_available/:url_to_check', to: 'custom_pages#url_available', as: 'url_available'
  end
  get 'custom_pages/url_available/:url_to_check', to: 'custom_pages#url_available'
  get ':id', to: 'custom_pages#show', as: 'show_custom_page'

  root 'markers#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :set_markers
  before_action :set_title

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: t("messages.access_denied")
  end

  rescue_from ActionController::RoutingError do |exception|
    error_404
  end

  private

  # toto bude potreba v budoucnu omezit podle zobrazene mapy
  # a zbytek nacitat AJAXem
  def set_markers
    @markers = Marker.all
  end

  def set_title
    @title = CustomPage::DEFAULT_TITLE
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  def authorize
    redirect_to root_url if current_user.blank?
  end

  def not_found
    raise ActionController::RoutingError.new("not found")
  end

  def error_404
    respond_to do |format|
      format.html { render "error_404", status: :not_found }
      format.js { render "error_404", status: :not_found  }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_css_id
    body_css_id = controller.controller_name + "_"
    body_css_id += controller.action_name == "create" ? "new" : controller.action_name
    body_css_id
  end
end

app/views/application/_content_box_end.html.erb
      </div>
    </div>
  </div>

app/views/application/_content_box_start.html.erb
<div id="content_outer_wrapper">
    <div id="content_inner_wrapper">
      <div id="close_button_box">
        <a href="#" id="close_button">close button<span></span></a>
      </div>
      <div id="content">

app/views/application/_default_response.js.erb
history.pushState({}, "", "<%= request.original_url %>");

if ($("div#content").length == 0) {
  loadAndShowContentBox("<%=j render controller.action_name %>");
}
else {
  $("div#content").empty().html("<%=j render controller.action_name %>");
}

app/views/application/_error_404.html.erb
<div id="flash_message">
  <div class="alert"><%= t("messages.not_found") %></div>
</div>

app/views/application/_flash.html.erb
<% if flash.any? %>
  <div id="flash_message">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
  </div>
<% end %>

app/views/application/_flash_response.js.erb
if ($("div#content").length == 0) {
  loadContentBox("");
}

history.pushState({}, "", "<%= root_url %>");
$("div#content").empty().html("<%=j render 'flash' %>");
contentBoxAutoWidth();

<% if !@permanentFlash %>
  autoHideContentBox();
<% end %>

app/views/application/_main_menu.html.erb
<nav id="main_menu">
  <ul>
    <li><%= image_tag "icon_menu.png", alt: t("menu.menu") %>
      <ul>
        <%= render "website_menu" %>
      </ul></li>
    <li class="right">
      <% if @current_user.present? %>
        <%= image_tag "icon_user_logged.png", alt: t("menu.user") %>
      <% else %>
        <%= image_tag "icon_user.png", alt: t("menu.user") %>
      <% end %>
      <ul>
        <% if @current_user.present? %>
          <%= render "user_menu_logged" %>
        <% else %>
          <%= render "user_menu_basic" %>
        <% end %>
      </ul></li>
  </ul>
</nav>

app/views/application/_user_menu_basic.html.erb
<li><%= link_to t("menu.login"), login_url, remote: true %></li>
<li><%= link_to t("menu.sign_up"), new_user_url, remote: true %></li>

app/views/application/_user_menu_logged.html.erb
<% if @current_user.admin? %>
  <li><%= link_to t("menu.custom_pages"), custom_pages_url, remote: true %></li>
  <li><%= link_to t("menu.users"), users_url, remote: true %></li>
<% end %>
<li><%= link_to t("menu.account"), user_url(@current_user), remote: true %></li>
<li><%= link_to t("menu.logout"), logout_url, method: :delete, remote: true %></li>

app/views/application/_website_menu.html.erb
<% CustomPage.where(active: true, show_in_menu: true).order(:position_in_menu).each do |custom_page| %>
  <li><%= link_to custom_page.title, show_custom_page_url(custom_page), remote: true %></li>
<% end %>

app/views/application/error_404.html.erb
<%= render "error_404" %>

app/views/application/error_404.js.erb
if ($("div#content").length == 0) {
  loadAndShowContentBox("<%=j render 'error_404' %>");
}
else {
  $("div#content").empty().html("<%=j render 'error_404' %>");
}